import 'enums.dart';

/// A single insight generated by the engine
class Insight {
  final String id;
  final InsightCategory category;
  final InsightSeverity severity;

  /// Localization key for the title
  final String titleKey;

  /// Localization key for the description
  final String descriptionKey;

  /// Dynamic arguments to pass into the localized string (for .tr(args: []))
  final List<String> titleArgs;
  final List<String> descriptionArgs;

  /// Named args for localization (for .tr(namedArgs: {}))
  final Map<String, String> titleNamedArgs;
  final Map<String, String> descriptionNamedArgs;

  /// Supporting metric data for display
  final Map<String, dynamic> metrics;

  /// Optional localization key for recommendation text
  final String? recommendationKey;
  final List<String> recommendationArgs;
  final Map<String, String> recommendationNamedArgs;

  /// Impact score 0-100. Higher = more important to address.
  final double impactScore;

  /// Which focus tags this insight belongs to
  final List<FocusTag> focusTags;

  /// Whether this was triggered by an anomaly
  final bool isAnomaly;

  const Insight({
    required this.id,
    required this.category,
    required this.severity,
    required this.titleKey,
    required this.descriptionKey,
    this.titleArgs = const [],
    this.descriptionArgs = const [],
    this.titleNamedArgs = const {},
    this.descriptionNamedArgs = const {},
    this.metrics = const {},
    this.recommendationKey,
    this.recommendationArgs = const [],
    this.recommendationNamedArgs = const {},
    this.impactScore = 50,
    this.focusTags = const [],
    this.isAnomaly = false,
  });

  Map<String, dynamic> toJson() => {
        'id': id,
        'category': category.name,
        'severity': severity.name,
        'titleKey': titleKey,
        'descriptionKey': descriptionKey,
        'titleArgs': titleArgs,
        'descriptionArgs': descriptionArgs,
        'titleNamedArgs': titleNamedArgs,
        'descriptionNamedArgs': descriptionNamedArgs,
        'metrics': metrics,
        'recommendationKey': recommendationKey,
        'recommendationArgs': recommendationArgs,
        'recommendationNamedArgs': recommendationNamedArgs,
        'impactScore': impactScore,
        'focusTags': focusTags.map((e) => e.name).toList(),
        'isAnomaly': isAnomaly,
      };
}

/// A concrete, actionable recommendation
class Recommendation {
  final String id;

  /// Localization key for the title
  final String titleKey;
  final Map<String, String> titleNamedArgs;

  /// Localization key for the description
  final String descriptionKey;
  final Map<String, String> descriptionNamedArgs;

  /// Estimated impact score 0-100
  final double impactScore;

  /// Related insight IDs
  final List<String> relatedInsightIds;

  /// Whether this is urgent (should be shown prominently)
  final bool isUrgent;

  /// Focus category this recommendation belongs to
  final InsightCategory category;

  const Recommendation({
    required this.id,
    required this.titleKey,
    required this.descriptionKey,
    required this.impactScore,
    required this.category,
    this.titleNamedArgs = const {},
    this.descriptionNamedArgs = const {},
    this.relatedInsightIds = const [],
    this.isUrgent = false,
  });

  Map<String, dynamic> toJson() => {
        'id': id,
        'titleKey': titleKey,
        'titleNamedArgs': titleNamedArgs,
        'descriptionKey': descriptionKey,
        'descriptionNamedArgs': descriptionNamedArgs,
        'impactScore': impactScore,
        'relatedInsightIds': relatedInsightIds,
        'isUrgent': isUrgent,
        'category': category.name,
      };
}

/// An alert that requires user attention
class InsightAlert {
  final String id;
  final InsightSeverity severity;
  final String titleKey;
  final Map<String, String> titleNamedArgs;
  final String descriptionKey;
  final Map<String, String> descriptionNamedArgs;
  final InsightCategory category;
  final bool requiresImmediateAction;

  const InsightAlert({
    required this.id,
    required this.severity,
    required this.titleKey,
    required this.descriptionKey,
    required this.category,
    this.titleNamedArgs = const {},
    this.descriptionNamedArgs = const {},
    this.requiresImmediateAction = false,
  });

  Map<String, dynamic> toJson() => {
        'id': id,
        'severity': severity.name,
        'titleKey': titleKey,
        'titleNamedArgs': titleNamedArgs,
        'descriptionKey': descriptionKey,
        'descriptionNamedArgs': descriptionNamedArgs,
        'category': category.name,
        'requiresImmediateAction': requiresImmediateAction,
      };
}
